# Generated by Django 5.0.1 on 2026-05-12 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('node', 'Node'), ('user', 'User'), ('system', 'System')], max_length=8)),
                ('actor_id', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('supported_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.node')),
            ],
            options={
                'verbose_name_plural': 'enrollment keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
