# Generated by Django 5.0.1 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_job_priority_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier, e.g. 'checksum'", max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema describing expected input_payload fields')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema describing the expected output format')),
                ('version', models.CharField(default='1.0.0', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workload type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='required_resources',
            field=models.JSONField(blank=True, default=dict, help_text='Resource requirements: {min_cpu_cores, min_memory_mb, min_disk_mb}'),
        ),
    ]
