# Generated by Django 5.0.1 on 2026-05-12 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Unique persistent device identifier', max_length=255, unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(blank=True, default='', help_text='e.g. windows, linux', max_length=32)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('enrolling', 'Enrolling'), ('active', 'Active'), ('idle', 'Idle'), ('busy', 'Busy'), ('degraded', 'Degraded')], db_index=True, default='offline', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.CharField(blank=True, default='', help_text='Bearer token for API auth', max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discovery_method', models.CharField(blank=True, default='manual', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_of', to='nodes.node')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NodeCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cores', models.IntegerField(default=0)),
                ('cpu_architecture', models.CharField(blank=True, default='', max_length=32)),
                ('memory_mb', models.IntegerField(default=0, help_text='Total RAM in MB')),
                ('disk_free_mb', models.IntegerField(default=0, help_text='Free disk in MB at time of report')),
                ('workload_types', models.JSONField(blank=True, default=list, help_text='List of supported workload type identifiers')),
                ('os_family', models.CharField(blank=True, default='', max_length=32)),
                ('os_distribution', models.CharField(blank=True, default='', max_length=128)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='nodes.node')),
            ],
            options={
                'verbose_name_plural': 'node capabilities',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=16)),
                ('current_load', models.FloatField(default=0.0, help_text='CPU load 0.0–1.0')),
                ('current_task', models.UUIDField(blank=True, help_text='Task ID if busy', null=True)),
                ('resources', models.JSONField(blank=True, default=dict, help_text='cpu_percent, memory_used_mb, disk_free_mb')),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='nodes.node')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
