# Generated by Django 5.0.1 on 2026-05-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='discovery_port',
            field=models.IntegerField(default=42069, help_text='UDP port for LAN discovery beacons'),
        ),
        migrations.AddField(
            model_name='node',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='nodes.cluster'),
        ),
        migrations.AddField(
            model_name='node',
            name='is_designated_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
